name: Build and Push obby-api Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  build:
    name: Build obby-api Image
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: obby-api
      context: .
      dockerfile: ./Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
